### ISSUE TITLE
Which machine are you running Slackware-loongarch64 on? Can I buy it on Taobao?

### ISSUE THREAD

**Issue by shamefulCake1** [slackwarecn/slackware-loongarch64#1]
$SUBJ

**Comment by shipujin** [comment]
You can buy them on Taobao
I developed and used slackwareloong on LoongArch3A5000 and 3A6000 machines

mirrors:
CN:
https://mirrors.nju.edu.cn/slackwareloong/
https://mirrors.wsyu.edu.cn/slackwareloong/

uk:
https://slackware.uk/slackwareloong/

**Comment by shamefulCake1** [comment]
Thanks！ 非常感谢！
